export const GET_USERS = {
    REQUEST: 'GET_USERS_REQUEST',
    SUCCESS: 'GET_USERS_SUCCESS',
    ERROR: 'GET_USERS_ERROR'
}

export const GET_POSTS = {
    REQUEST: 'GET_POSTS_REQUEST',
    SUCCESS: 'GET_POSTS_SUCCESS',
    ERROR: 'GET_POSTS_ERROR'
}